### ISSUE TITLE
No movement of paddle if monochromatic frequency above 1.5 Hz or so

### ISSUE THREAD

**Issue by rickyspaceguy** [LHEEA/HOS-NWT#11]
Attached input_HOS-NWT.txt. If `nu_mono>1.5 Hz` no paddle motions are registered. Happens even if `icase` is not equal to 2 but `nu_mono` is set to be greater than 1.5 Hz. 

Actually, it has been observed that even this value of 1.5 Hz is not consistent as it seems to depend upon tank dimensions. This is one such example. If such a situation is encountered, no matter what value of `icase` is, the paddle motions won't register any movement.

The dependence on tank dimensions is making debugging difficult.
[input_HOS-NWT.txt](https://github.com/LHEEA/HOS-NWT/files/1391760/input_HOS-NWT.txt)

**Comment by gducrozet** [comment]
There was indeed an issue for `icase=2`. However, this should be limited to this test case. If you encountered similar problem for other values of `icase`, please provide an example.

By the way, to treat this issue, the file `wavemaking.f90` should be modified:
- line 105 should be replaced by: n_max  = MAX(1,2**wav%config%rnum / n_max)

This slight modification ensures that at least one frequency is taken into account in the definition of the wavemaker motion.
