### ISSUE TITLE
problem on installation and usage.

### ISSUE THREAD

**Issue by jiezhanghydro** [LHEEA/HOS-NWT#12]
Hello, 
Thank you for sharing this source to the public. I plane to use HOS-NWT to generate focused wave for my research, which is carried out at Osaka University Japan. I am using ifort to compile this program. To be honest, I am not familiar with the Linux/Unix environment, I have some problems with installation. 

1. I can not find **makedepf90** and where should I put this file? Here is some problem when compiling.

[earlyup@pc1-64hpc wave]$ make Debug -B
exists
exists
exists
rm -f obj/.depend
makedepf90 -b obj/ sources/main/HOS-NWT.f90 sources/main/wavemaking.f90 sources/main/filtering.f90 sources/main/dealiasing.f90 sources/main/resol_HOS.f90 sources/main/resol_wmkr.f90 sources/main/initial_condition.f90   sources/variabledef/variables.f90 sources/variabledef/common_vars.f90 sources/variabledef/type.f90  sources/wave/definition2.f90 sources/wave/config_def.f90 sources/wave/read_ocean_txt.f90 sources/wave/wave_def.f90 sources/wave/linear_wave.f90  sources/fourier/fourier_FFTW.f90 sources/timeintegration/runge_kutta.f90 sources/timeintegration/variablechange.f90 sources/IO/input.f90 sources/IO/vol_energy.f90 sources/IO/velocities.f90 sources/IO/output.f90 > obj/.depend
/bin/sh: makedepf90: command not found
make: *** [obj/.depend] Error 127

2. I plane to study the interaction between focused wave and a fixed FPSO by fully nonlinear potential flow theory. In such case, could I take the focused wave field as an explicit input and only compute the disturb wave field? Regarding embedding HOS-NWT on my time-domain BEM solver and the methodology itself, could you give some comments or advice? Thank you very much!

**Comment by jiezhanghydro** [comment]
Thank you very much for your quick reply! I would try according to this file provided. 
: )

**Comment by gducrozet** [comment]
Thank you @rickyspaceguy for the prompt reply.

@jiezhanghydro Regarding your second point about the interaction between a focused wave and a FPSO:

- the strategy of using HOS-NWT to define the incident wave field as an explicit input and only solving for the disturbed wave field should work, dependent on the exact methodology used for the coupling...

- The simpler methodology to embed HOS-NWT in your BEM solver is probably to use relaxation zones. In a given spatial region, you force the solution to change from the only incident wave field (given by HOS) up to the full solution (incident + diffracted) obtained by BEM. The focused wave being localized in space and time, you should be able to consider a quite limited time & spatial extent for your BEM solution.

- Another methodology may be to solve in your BEM only the effect of the structure on the incident wave field. This is achieved by modifying the set of equations solved in the BEM model, making the incident wave field act as forcing terms in the model. This is the so-called SWENSE method developed at ECN - LHEEA. If needed, I can provide you reference relative to this method.

Guillaume.

**Comment by rickyspaceguy** [comment]
While Dr. Ducrozet has been very humble in not burdening you with information overload, I would point out that you can interface your programme/code/software package with another package released by LHEEA for this purpose i.e. [Grid2Grid](https://github.com/LHEEA/Grid2Grid).

If you already know the ropes for HOS-Ocean/HOS-NWT, then Grid2Grid code is easy peasy lemon squeezy. Indeed it is very well written and documented. Moreover, it uses the so-called SWENSE output generated by the related HOS programmes of LHEEA. 

In my opinion, you don't need to learn about SWENSE if you are constrained for time. By the time one is familiar with HOS, SWENSE is easy to understand.

**Comment by yayihhu** [comment]
I have met the same problem as your 1st problem. Had you solved this problem? If you can tell me some details of the solution, it will help my intial study more enthusiasm.
Thank you, very much.

root@ubuntu:/home/yayi/Desktop/HOS-NWT-1.2# make all
rm -f obj/*
rm -f obj/.depend
rm -f bin/HOS-NWT
all cleaned up!
exists
exists
exists
rm -f obj/.depend
makedepf90 -b obj/ sources/main/HOS-NWT.f90 sources/main/wavemaking.f90 sources/main/filtering.f90 sources/main/dealiasing.f90 sources/main/resol_HOS.f90 sources/main/resol_wmkr.f90 sources/main/initial_condition.f90   sources/variabledef/variables.f90 sources/variabledef/common_vars.f90 sources/variabledef/type.f90  sources/wave/definition2.f90 sources/wave/config_def.f90 sources/wave/read_ocean_txt.f90 sources/wave/wave_def.f90 sources/wave/linear_wave.f90  sources/fourier/fourier_FFTW.f90 sources/timeintegration/runge_kutta.f90 sources/timeintegration/variablechange.f90 sources/IO/input.f90 sources/IO/vol_energy.f90 sources/IO/velocities.f90 sources/IO/output.f90 > obj/.depend
/bin/sh: 1: makedepf90: not found
makefile:136: recipe for target 'depend' failed
make: *** [depend] Error 127
