### ISSUE TITLE
Problem on usage

### ISSUE THREAD

**Issue by Sujunwei123** [LHEEA/HOS-NWT#14]
Hello, I am a student from Hohai university. I have installed the ubuntu system and downloaded the HOS-NWT-1.2 package from this website, but I don't know how to run HOS-NWT. Maybe I am a beginner. Can you tell me the detailed steps for running this program？How to compile and link？I am really looking forward to your reply, thank you very much！

**Comment by YoungmChoi** [comment]
Dear Sujunwei123, 

Thank you for using HOS. To install HOS-NWT, you should install some libraries on your Ubuntu. 
HOS installation procedures are given in Grid2Grid manual. It is available on Github also. 

Please see it and send us a mail if you face a problem or difficulties :) 

Have a nice day ! 

Best Regards, 
YoungMyung Choi
