### ISSUE TITLE
An error occurred when compile HOS-NWT

### ISSUE THREAD

**Issue by Fitanium** [LHEEA/HOS-NWT#20]
1. At first, I created a new folder named `build` in the **cmake** directory
2. And, I opened a terminal, changed the working directory into `build`, typed the command `cmake .. -DCMAKE_BUILD_TYPE=Release`
3. Everything was going well before I typed `make`, the information are as follows

![image](https://user-images.githubusercontent.com/28805527/50268874-583c4c00-0467-11e9-9fc3-7616598620f6.png)

Then I checked the code, I found that `p2` has been defined as an integer parameter variable with value 1 in `common_vars.f90`,  So the compiler reported an error.

**Comment by Fitanium** [comment]
I modified the value of `p2`, and finished compiling the code without error.

**Comment by rickyspaceguy** [comment]
@Fitanium 

Change `MOD` to `MODULO`. 

`p2=1` means a wave flume

See issue #18
