### ISSUE TITLE
JONSWAP spectrum wave generation issue

### ISSUE THREAD

**Issue by handrake0724** [LHEEA/HOS-NWT#21]
I am trying to generate JONSWAP spectrum irregular wave with Hs=17.3 and Tp.16.65 and gamma=3.15 for. model scale is 50 and Hs and Tp are scaled.
I guess this spectrum should be generated because the waves can be easily generated in normal wave basin test. However, simulation generate NaN after some running.

input is as follows:
1   ----------------------- Tank dimensions -----------------------                                                                                                                                             
  1 Length(m) of the wavetank    :: xlen             :: 120.0d0                                                                                                                                                 
  2 Beam(m) of the wavetank      :: ylen             :: 100.d0                                                                                                                                                  
  3 Depth(m) of the wavetank     :: h                :: 5.d0                                                                                                                                                    
  4 ------------------------ Select case --------------------------                                                                                                                                             
  5 Choice of computed case      :: icase            :: 4                                                                                                                                                       
  6 ------------------ Sloshing case (icase = 1) ------------------                                                                                                                                             
  7 Number of the natural mode   :: islosh           :: 3                                                                                                                                                       
  8 Amplitude (m) of the mode    :: aslosh           :: 0.2d0                                                                                                                                                   
  9 --------------- Monochromatic case (icase = 2) ----------------                                                                                                                                             
 10 Amplitude (m) of wave train  :: amp_mono         :: 0.1d0                                                                                                                                                   
 11 Frequency (Hz) of wave train :: nu_mono          :: 0.5588d0                                                                                                                                                
 12 Angle (deg) from x-axis      :: theta_mono       :: 0.d0                                                                                                                                                    
 13 Phasis (rad) of wave train   :: ph_mono          :: 0.d0                                                                                                                                                    
 14 Directional wmk type         :: ibat             :: 2                                                                                                                                                       
 15 Wave target distance (ibat=3):: xd_mono          :: 18.d0                                                                                                                                                   
 16 -------------------- File case (icase = 3) --------------------                                                                                                                                             
 17 Name of frequency file       :: file_name        :: Hs4_Tp10                                                                                                                                                
 18 Frequency cut-off            :: i_cut            :: 0                                                                                                                                                       
 19 Low cut_off frequency (Hz)   :: nuc_low          :: 0.3d0                                                                                                                                                   
 20 High cut_off frequency (Hz)  :: nuc_high         :: 3.d0                                                                                                                                                    
 21 ------------------ Irregular wave (icase=4) -------------------                                                                                                                                             
 22 Significant wave height (m)  :: Hs               :: 0.346d0                                                                                                                                                 
 23 Peak period (s)              :: Tp               :: 2.3547d0                                                                                                                                                
 24 Shape factor (Jonswap)       :: gamma            :: 3.15d0                                                                                                                                                  
 25 Seed number for random numb. :: iseed            :: 513                                                                                                                                                     
 26 -------------------- Wavemaker definition ---------------------                                                                                                                                             
 27 Nonlinear order of wavemaker :: i_wmk            :: 2                                                                                                                                                       
 28 Type (1: piston, 2: hinged)  :: igeom            :: 2                                                                                                                                                       
 29 Rotation axis distance       :: d_hinge          :: 1.d0                                                                                                                                                    
 30 Time ramp                    :: iramp            :: 1                                                                                                                                                       
 31 Time ramp duration (s)       :: Tramp            :: 5.0d0                                                                                                                                                   
 32 ----------------------- Numerical beach -----------------------                                                                                                                                             
 33 Absorption numerical beach   :: iabsnb           :: 1                                                                                                                                                       
 34 Beginning front num. beach   :: xabsf            :: 0.8d0                                                                                                                                                   
 35 Absorption strength front    :: coeffabsf        :: 1.d0                                                                                                                                                    
 36 ------------- Elevation/Velocity-Pressure probes --------------                                                                                                                                             
 37 Use of probes                :: iprobes          :: 1                                                                                                                                                       
 38 Filename of probe positions  :: pro_file         :: prob.inp                                                                                                                                                
 39 ---------------------- Time-integration -----------------------                                                                                                                                             
 40 Duration of the simulation   :: T_stop           :: 1528.0d0                                                                                                                                                
 41 Time tolerance: RK 4(5)      :: toler            :: 1.e-4                                                                                                                                                   
 42 Output frequency             :: f_out            :: 30.d0                                                                                                                                                   
 43 --------------------------- Output ----------------------------                                                                                                                                             
 44 Output: 1-dim. ; 0-nondim.   :: idim             :: 1                                                                                                                                                       
 45 free surface plot            :: i3d              :: 0                                                                                                                                                       
 46 modes plot                   :: imodes           :: 0                                                                                                                                                       
 47 wavemaker motion plot        :: iwmk             :: 0                                                                                                                                                       
 48 Swense output 1='yes',0='no' :: i_sw             :: 0

**Comment by gducrozet** [comment]
@handrake0724 
Could you please provide me the numerical parameters at use in common_vars.f90?

Regards,
Guillaume

**Comment by handrake0724** [comment]
common_vars.f90 is as follows:

30 ! Number of modes
 29 INTEGER, PARAMETER :: n1 = 513
 28 INTEGER, PARAMETER :: n2 = 1
 27 INTEGER, PARAMETER :: n3 = 33
 26 ! HOS nonlinearity order
 25 INTEGER, PARAMETER :: mHOS = 3
 24 ! Dealiasing parameters
 23 INTEGER, PARAMETER :: p1 = mHOS
 22 INTEGER, PARAMETER :: p2 = 1
 21 ! Number of modes with the extended grid
 20 INTEGER, PARAMETER :: Nd1 = ((p1+1) * n1) / 2 ! required modes
 19 INTEGER, PARAMETER :: Nd2 = ((p2+1) * n2) / 2 ! required modes
 18 ! Possible filtering in each direction
 17 REAL(RP), DIMENSION(3), PARAMETER :: coeffilt = (/1.0_rp, 1.0_rp, 1.0_rp/)
 16 ! Max number of probes in files
 15 INTEGER, PARAMETER :: maxprobes = 10
 14 ! Wavemaker definition
 13 INTEGER, PARAMETER :: l_add=2, n3_add = l_add*(n3-1)
 12 !-
 11 INTEGER, PARAMETER :: mHOSdiv2m1 = MAX(1,mHOS / 2 - 1), mHOSm3div2 = MAX(1,(mHOS-3) / 2)
 10 !
  9 ! Variables definition for possible specification of n1,n2,n3,mHOS in input files
  8 INTEGER, PARAMETER :: m1=n1, m2=n2, m3=n3, maxm1m2 = max(m1,m2)
  7 INTEGER, PARAMETER :: m3_add = l_add*(m3-1)
  6 INTEGER, PARAMETER :: maxHOS=mHOS, p1max=p1, p2max=p2
  5 INTEGER, PARAMETER :: md1 = (m1*(p1max+1))/2+1, md2 = (m2*(p2max+1))/2+1 !dealiased
  4 INTEGER, PARAMETER :: tecplot = 11, iCPUtime = 0 ! For possible time output of each routine-

NaN appears  after 38.2 sec.

**Comment by rickyspaceguy** [comment]
Do you compile your program from the makefile in `Debug` mode or `Release` mode? 

Change it to run in `Debug` mode by changing the line in the `makefile`

`all:clean depend Release`

 to 

`all:clean depend Debug`
 
and run the program with a debugger like `gdb`. However, note that is going to take a lot more time to run in the `Debug` mode.

**Comment by handrake0724** [comment]
I found in the log the following
    volume =   1.1446E-03 t=  3.8133E+01 timestep: 1.2273E-02  2590  1155
 etax   56.803424064345528                2           1
******************** Slope of FS elevation too high ******************** 
Trying to filter eta and phis...
    volume =  -4.3449E-03 t=  3.8167E+01 timestep: 1.2456E-03  2604  1168
    volume =          NaN t=  3.8200E+01 timestep: 2.8623E-02  2664  1198
    volume =          NaN t=  3.8233E+01 timestep: 2.8482E-02  2666  1199
    volume =          NaN t=  3.8267E+01 timestep: 2.7222E-02  2668  1200
    volume =          NaN t=  3.8300E+01 timestep: 2.6364E-02  2670  1201

and the wave elevation at probe1 is as below. So, it looks like wave steepness is the problem.
my colleague says the wave condition is not that severe condition. then, tank domain: length and depth is not engough?

![eta](https://user-images.githubusercontent.com/18005991/57924926-75275f00-78e1-11e9-87cd-8d517bd416a1.png)

**Comment by rickyspaceguy** [comment]
The wave is locally breaking. Hence the computation breaks down. 

However, if you are completely sure that this is a non-breaking wave, you can play with the the number of modes `n1` & `toler`.  I don't think the length & depth are the issue although `n1=1025` or above should suffice. Setting `toler=1e-7` or above is also good. 

But I think the the waveform is locally plunging. You can verify that in another MEL type code if experimental values are unavailable.

**Comment by handrake0724** [comment]
Increasing n1 did not work.
Instead changing nonlinearity order 3 to 5 looks working but not sure and need to watch more.

**Comment by Naaba** [comment]
Hi, I think it is significantly steep and it is not strange that you have
local breaking event that blows up the simulation without a breaking model.

Le ven. 17 mai 2019 à 13:24, handrake0724 <notifications@github.com> a
écrit :

**Comment by gducrozet** [comment]
The characteristic steepness of your wave field may be evaluated through the ratio (Hs/lambdap), which is 0.04 in your case. This is consequently quite steep and you may face breaking event.

One possibility is to reduce the accuracy of the solution, removing higher frequencies by reducing the number of points in your simulation (i.e. n1).
In the present configuration, the shortest wave solved has a wavenumber k_max = (n1-1)*pi/Lx = 13.4 rad/s which corresponds to k_max = 18 * k_p which is a quite standard discretization for HOS-NWT. reducing n1 will probably alter a bit the accuracy but will help preventing the appearance of breaking events.

**Comment by DoubleMiaoLi** [comment]
Hello！I am trying to generate JONSWAP spectrum irregular wave using your parameters. Why the results of probes.dat is this?
<img width="448" alt="1" src="https://github.com/LHEEA/HOS-NWT/assets/103564643/de9ac68b-ef9c-4aa4-b727-3ecd69ddb2b4">

**Comment by DoubleMiaoLi** [comment]
@handrake0724  Hello, I'm trying to generate JONSWAP spectrum irregular wave using your parameters. Why the results of probes.dat is this?
<img width="448" alt="1" src="https://github.com/LHEEA/HOS-NWT/assets/103564643/b1c7c8b7-b619-4f83-910a-ad5ed06c0208">

---------------------------------------------------------------------------------
The parameters in input_HOS-NWT.dat are:

----------------------- Tank dimensions -----------------------
Length(m) of the wavetank    :: xlen             :: 46.4d0
Beam(m) of the wavetank      :: ylen             :: 29.74d0
Depth(m) of the wavetank     :: h                :: 5.d0
------------------------ Select case --------------------------
Choice of computed case      :: icase            :: 4
------------------ Sloshing case (icase = 1) ------------------
Number of the natural mode   :: islosh           :: 3
Amplitude (m) of the mode    :: aslosh           :: 0.2d0
--------------- Monochromatic case (icase = 2) ----------------
Amplitude (m) of wave train  :: amp_mono         :: 0.1d0
Frequency (Hz) of wave train :: nu_mono          :: 0.546875d0
Angle (deg) from x-axis      :: theta_mono       :: 0.d0
Phasis (rad) of wave train   :: ph_mono          :: 0.d0
Directional wmk type         :: ibat             :: 2
Wave target distance (ibat=3):: xd_mono          :: 18.d0
-------------------- File case (icase = 3) --------------------
Name of frequency file       :: file_name        :: CAT1__22
Frequency cut-off            :: i_cut            :: 0
Low cut_off frequency (Hz)   :: nuc_low          :: 0.3d0
High cut_off frequency (Hz)  :: nuc_high         :: 3.d0
------------------ Irregular wave (icase=4) -------------------
Significant wave height (m)  :: Hs               :: 0.03d0
Peak period (s)              :: Tp               :: 1.d0
Shape factor (Jonswap)       :: gamma            :: 3.3d0
Seed number for random numb. :: iseed            :: 513
-------------------- Wavemaker definition ---------------------
Nonlinear order of wavemaker :: i_wmk            :: 2
Type (1: piston, 2: hinged)  :: igeom            :: 2
Rotation axis distance       :: d_hinge          :: 2.147d0
Time ramp                    :: iramp            :: 1
Time ramp duration (s)       :: Tramp            :: 3.0d0
----------------------- Numerical beach -----------------------
Absorption numerical beach   :: iabsnb           :: 1
Beginning front num. beach   :: xabsf            :: 0.8d0
Absorption strength front    :: coeffabsf        :: 1.d0
------------- Elevation/Velocity-Pressure probes --------------
Use of probes                :: iprobes          :: 1
Filename of probe positions  :: pro_file         :: prob.inp
---------------------- Time-integration -----------------------
Duration of the simulation   :: T_stop           :: 40.0d0
Time tolerance: RK 4(5)      :: toler            :: 1.e-4
Output frequency             :: f_out            :: 10.d0
--------------------------- Output ----------------------------
Output: 1-dim. ; 0-nondim.   :: idim             :: 1
free surface plot            :: i3d              :: 0
modes plot                   :: imodes           :: 0
wavemaker motion plot        :: iwmk             :: 1
Swense output 1='yes',0='no' :: i_sw             :: 0

-------------------------------------------------------------------------------------------------
The parameters in common_var.f90 are:

IMPLICIT NONE
!
! Number of modes
INTEGER, PARAMETER :: n1 = 513
INTEGER, PARAMETER :: n2 = 1
INTEGER, PARAMETER :: n3 = 33
! HOS nonlinearity order
INTEGER, PARAMETER :: mHOS = 3
! Dealiasing parameters
INTEGER, PARAMETER :: p1 = mHOS
INTEGER, PARAMETER :: p2 = mHOS
! Number of modes with the extended grid
INTEGER, PARAMETER :: Nd1 = ((p1+1) * n1) / 2 ! required modes
INTEGER, PARAMETER :: Nd2 = ((p2+1) * n2) / 2 ! required modes
! Possible filtering in each direction
REAL(RP), DIMENSION(3), PARAMETER :: coeffilt = (/1.0_rp, 1.0_rp, 1.0_rp/)
! Max number of probes in files
INTEGER, PARAMETER :: maxprobes = 10
! Wavemaker definition
INTEGER, PARAMETER :: l_add=2, n3_add = l_add*(n3-1)
! 
INTEGER, PARAMETER :: mHOSdiv2m1 = MAX(1,mHOS / 2 - 1), mHOSm3div2 = MAX(1,(mHOS-3) / 2)
!
! Variables definition for possible specification of n1,n2,n3,mHOS in input files
INTEGER, PARAMETER :: m1=n1, m2=n2, m3=n3, maxm1m2 = max(m1,m2)
INTEGER, PARAMETER :: m3_add = l_add*(m3-1)
INTEGER, PARAMETER :: maxHOS=mHOS, p1max=p1, p2max=p2
INTEGER, PARAMETER :: md1 = (m1*(p1max+1))/2+1, md2 = (m2*(p2max+1))/2+1 !dealiased
INTEGER, PARAMETER :: tecplot = 11, iCPUtime = 0 ! For possible time output of each routine 
!
!
!
END MODULE common_vars


-----------------------------
what can I do to solve this problem? Thank you!
 This is my emails: limiaomiao181@mails.ucas.ac.cn

**Comment by gducrozet** [comment]
Hello @DoubleMiaoLi,
I assume that you did not specify a probe location in the file prob.inp and consequently you just have a file probes.dat with one colum, which is the time.
