### ISSUE TITLE
Wavemaker with limited length

### ISSUE THREAD

**Issue by taertsens** [LHEEA/HOS-NWT#27]
Hi everyone

I'm trying to use HOS-NWT for a basin with a wavemaker which has a limited length. I read in the PhD thesis of Félicien Bonnefoy that he adapted the code for the specific case of the B600 towing tank of DWA. His adaptations should be described in the study report 'Etude numérique de la faisabilité de la génération de houles obliques au B600 avec un batteur latéral'. However, I can't find that report anywhere on the web. By going through the code, I saw that the implementation is still present in the different subroutines, but that the necessary input parameters need to be added to the input file and read by the algorithm. If I'm not mistaken, the situation of a wavemaker on only a part of the side can be activated by setting 'iwidth' to two. Doing so, eight more parameters need to be defined: ywmk, yl, yr, y_rmp, yabsl, yabsr, coeffabsl and coeffabsr.

I'm not sure what the variable y_rmp stands for. I assume that it has something to do with the shape of the absorbing beaches next to the wavemaker in the y-direction, but I haven't a clue on its exact definition. Anyone who can help me with this? Any other tips on how to use HOS-NWT for a wavemaker with limited length are welcome as well.

Thanks in advance!
Tim

**Comment by gducrozet** [comment]
@taertsens Sorry, you request was lost in my email flux and I see that it is now closed.
If needed, I can probably send you the corresponding report.

Regarding y_rmp, it defines the spatial ramp defining the shape of the lateral wavemaker. If you look inside wavemaking.f90, the definition is quite obvious.

Best,
Guillaume

**Comment by taertsens** [comment]
Dear Guillaume,

No problem, I managed to figure it out myself. At first, I was confusing it with the ramps of the absorbing beaches, but after inspecting wavemaking.f90 in more detail, it was indeed quite obvious.

Thanks for your response and for the very interesting code!!

Kind regards,
Tim
