### ISSUE TITLE
Low frequency wave simulaiton

### ISSUE THREAD

**Issue by nbcm** [LHEEA/HOS-NWT#3]
Hello,

I am the learner of the HOS-NWT. I am trying to simulate a 0.29m height and T = 3s (freq = 0.3333) regular wave. When I run the package, there is a SIGFPE error (floating-point exception) and it seems happened in routine wnk_ini. Anyone hase the same problem? How to deal this?

**Comment by gducrozet** [comment]
Hello,

Few questions to try to understand the problem : 
    - Did you manage to perform other simulations with HOS-NWT? Is it this specific case which is not working?
    - What are the characteristics of the basin? depth/wavemaker type/length/discretization/HOS order
    - Do you have the same problem fixing order of nonlinearity M=1 and i_wmk=1
    - Did you try running in Debug mode to have more detailed informations about the possible problem?

Best regards,

Guillaume.

**Comment by nbcm** [comment]
I just run the regular_2D example in /bin and when the frequency (nu_mono) less than 0.5, SIGFPE error come up.

**Comment by nbcm** [comment]
I have back tracked the error and it located in wavemaking.f90, line 104 and 105
n_max  = FLOOR((wav%config%clock * SQRT(g / wav%config%depth)))
n_max  = 2**wav%config%rnum / n_max

In the case, when nu_mono less than 0.5, the FlOOR( )=0 and n_max blow up to inf.

**Comment by gducrozet** [comment]
Could you post your input file?

Especially, I wondered what is the water depth you used?

**Comment by nbcm** [comment]
----------------------- Tank dimensions -----------------------
Length(m) of the wavetank    :: xlen             :: 46.4d0
Beam(m) of the wavetank      :: ylen             :: 29.74d0
Depth(m) of the wavetank     :: h                :: 5.d0
------------------------ Select case --------------------------
Choice of computed case      :: icase            :: 2
------------------ Sloshing case (icase = 1) ------------------
Number of the natural mode   :: islosh           :: 3
Amplitude (m) of the mode    :: aslosh           :: 0.2d0
--------------- Monochromatic case (icase = 2) ----------------
Amplitude (m) of wave train  :: amp_mono         :: 0.1d0
Frequency (Hz) of wave train :: nu_mono          :: 0.49d0
Angle (deg) from x-axis      :: theta_mono       :: 0.d0
Phasis (rad) of wave train   :: ph_mono          :: 0.d0
Directional wmk type         :: ibat             :: 2
Wave target distance (ibat=3):: xd_mono          :: 18.d0
-------------------- File case (icase = 3) --------------------
Name of frequency file       :: file_name        :: focusSPH
Frequency cut-off            :: i_cut            :: 0
Low cut_off frequency (Hz)   :: nuc_low          :: 0.3d0
High cut_off frequency (Hz)  :: nuc_high         :: 3.d0
------------------ Irregular wave (icase=4) -------------------
Significant wave height (m)  :: Hs               :: 0.05d0
Peak period (s)              :: Tp               :: 1.d0
Shape factor (Jonswap)       :: gamma            :: 3.3d0
Seed number for random numb. :: iseed            :: 513
-------------------- Wavemaker definition ---------------------
Nonlinear order of wavemaker :: i_wmk            :: 2
Type (1: piston, 2: hinged)  :: igeom            :: 2
Rotation axis distance       :: d_hinge          :: 2.147d0
Time ramp                    :: iramp            :: 1
Time ramp duration (s)       :: Tramp            :: 3.0d0
----------------------- Numerical beach -----------------------
Absorption numerical beach   :: iabsnb           :: 1
Beginning front num. beach   :: xabsf            :: 0.8d0
Absorption strength front    :: coeffabsf        :: 1.d0
------------- Elevation/Velocity-Pressure probes --------------
Use of probes                :: iprobes          :: 1
Filename of probe positions  :: pro_file         :: prob.inp
---------------------- Time-integration -----------------------
Duration of the simulation   :: T_stop           :: 40.0d0
Time tolerance: RK 4(5)      :: toler            :: 1.e-6
Output frequency             :: f_out            :: 20.d0
--------------------------- Output ----------------------------
Output: 1-dim. ; 0-nondim.   :: idim             :: 1
free surface plot            :: i3d              :: 1
modes plot                   :: imodes           :: 0
wavemaker motion plot        :: iwmk             :: 1
Swense output 1='yes',0='no' :: i_sw             :: 0

**Comment by nbcm** [comment]
I also tracked the value of wav%config%clock and wav%config%depth and the value of n_max by
n_max  = FLOOR((wav%config%clock * SQRT(g / wav%config%depth)))

Wave first order
 clock=  0.69964313023426161     
 depth=   5.0000000000000000     
 n_max=           0

Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

**Comment by gducrozet** [comment]
OK, I got the same problem. I will have a look at it on Monday.

Best regards.

Guillaume.

**Comment by nbcm** [comment]
what I am doing is add 
if ( n_max.eq.0 ) then
   n_max=1
end if

it works and make sense to me in physical but I am not sure.

**Comment by gducrozet** [comment]
Your correction is OK.

I updated the code (new commit) to correct the problem.
https://github.com/LHEEA/HOS-NWT/commit/f4d591569c251995556100d328b186fb2798c311
