### ISSUE TITLE
No Output

### ISSUE THREAD

**Issue by DoubleMiaoLi** [LHEEA/HOS-NWT#36]
<img width="1045" alt="福昕截屏20240426121709301" src="https://github.com/LHEEA/HOS-NWT/assets/103564643/3de08853-8eb0-464f-aab4-bb5407f2ed5f">
I conducted "make clean" and "make" steps. But there is no output in the 'Results' file. 
How to solve this problem? Thank you.

**Comment by gducrozet** [comment]
You need to execute the code... 
`./HOS-NWT`
