### ISSUE TITLE
In the wavemaking.f90 module of HOS-NWT, are the nodes 1-n3 in pos_1st uniformly distributed along the water depth direction?

### ISSUE THREAD

**Issue by banzhiqing** [LHEEA/HOS-NWT#41]
Dear Author,

Greetings! I am currently encountering some issues while working with the HOS-NWT model and would greatly appreciate your assistance. The specific problems are as follows:

1. In the wavemaking.f90 module of HOS-NWT, are the nodes 1-n3 in pos_1st uniformly distributed along the water depth direction? I noticed that your paper titled "Nonlinear Deterministic Sea Wave Prediction Using Instantaneous Velocity Profiles" might have utilized this module. Could you kindly confirm whether you replaced dpos1stdt(i3,i2) and d2pos1stdt2(i3,i2) with synthesized horizontal velocity and horizontal acceleration? If my understanding is correct, would it be feasible to use a set of horizontally distributed velocities and accelerations along the water depth to replace dpos1stdt(i3,i2) and d2pos1stdt2(i3,i2), thereby utilizing HOS-NWT for wave propagation?

2. During the post-processing of HOS-NWT, I noticed that the output horizontal velocities are not uniformly distributed along the water depth. Instead, the spacing between adjacent velocity output points in the z-direction becomes smaller as they approach the still water surface. If I set i_zvect in input_post_process.dat to the same value as n3, will the spatial positions of these velocity output points (in the water depth direction) correspond to the 1-n3 nodes?

Sincerely,
Ban Zhiqing.

<img width="495" alt="2e1f2f92cd073dad9a4d4b3e3c51860" src="https://github.com/user-attachments/assets/de31ef39-9340-4386-8c53-8982728303ab">
<img width="738" alt="5ace1e4f13d591e8293385d93a4db6e" src="https://github.com/user-attachments/assets/01e9ab97-d950-45e9-a0da-633a8742cff8">

**Comment by gducrozet** [comment]
Dear @banzhiqing 

As stated in the front page of the repository

> This project has migrated to [GitLab](https://gitlab.com/lheea/HOS-NWT). This repository will be kept in its current state (at the time of migration), but new developments will only be added to the new repository. Please only submit issues and new developments in the new repository.

For short answer to your questions (but please go to the new place for detailed discussion on this)

1. Yes, this is uniformly distributed. In the paper you referenced, we indeed modified the variables you indicate with synthetized horizontal velocity and acceleration

2. The post processing is totally independent of the solution of HOS-NWT. Especially, the vertical discretization of the wavemaker is not linked to the one you choose to postprocess the data. Then, choosing i_zvect=n3 will not provide you the same vertical locations. If you want to do so, you need to modify the zvect defintiion in the post-processing routines

**Comment by banzhiqing** [comment]
> 亲爱的
> 
> 如存储库首页所述
> 
> > 此项目已迁移到 [GitLab](https://gitlab.com/lheea/HOS-NWT)。此存储库将保持其当前状态（在迁移时），但新的开发将仅添加到新存储库中。请仅在新存储库中提交问题和新开发。
> 
> 要简短回答您的问题（但请到新的地方详细讨论）
> 
> 1. 是的，这是均匀分布的。在您引用的论文中，我们确实修改了您用合成的水平速度和加速度指示的变量
> 2. 后处理完全独立于 HOS-NWT 的解决方案。特别是，wavemaker 的垂直离散化与您选择对数据进行后处理的 wavemaker 无关。然后，选择 i_zvect=n3 将不会为您提供相同的垂直位置。如果要这样做，则需要在后处理例程中修改 zvect 定义

Dear @gducrozet 

Thank you very much for your kind assistance. I will continue to explore this matter, and should I have any further questions, I will seek your guidance on GitLab.

Best regards,
