### ISSUE TITLE
Swense output in 3D

### ISSUE THREAD

**Issue by Emix63** [LHEEA/HOS-NWT#5]
Hello!
I'm currently working on a wave generation and propagation subject and so I'm really interested in your HOS method.
After doing several simulations with the attached benchmark cases and in 2D, I'm willing to use the swense Output as an input in an other software. My problem is that in 3D, I have non numerical results in the .dat, which make it unusable with the Post processing program. 
Here is the input_HOS-NWT.dat :
----------------------- Tank dimensions -----------------------
Length(m) of the wavetank    :: xlen             :: 46.4d0
Beam(m) of the wavetank      :: ylen             :: 29.74d0
Depth(m) of the wavetank     :: h                :: 5.d0
------------------------ Select case --------------------------
Choice of computed case      :: icase            :: 31
------------------ Sloshing case (icase = 1) ------------------
Number of the natural mode   :: islosh           :: 3
Amplitude (m) of the mode    :: aslosh           :: 0.2d0
--------------- Monochromatic case (icase = 2) ----------------
Amplitude (m) of wave train  :: amp_mono         :: 0.1d0
Frequency (Hz) of wave train :: nu_mono          :: 0.546875d0
Angle (deg) from x-axis      :: theta_mono       :: 0.d0
Phasis (rad) of wave train   :: ph_mono          :: 0.d0
Directional wmk type         :: ibat             :: 2
Wave target distance (ibat=3):: xd_mono          :: 18.d0
-------------------- File case (icase = 3) --------------------
Name of frequency file       :: file_name        :: CAT1__22
Frequency cut-off            :: i_cut            :: 0
Low cut_off frequency (Hz)   :: nuc_low          :: 0.3d0
High cut_off frequency (Hz)  :: nuc_high         :: 3.d0
------------------ Irregular wave (icase=4) -------------------
Significant wave height (m)  :: Hs               :: 0.05d0
Peak period (s)              :: Tp               :: 1.d0
Shape factor (Jonswap)       :: gamma            :: 3.3d0
Seed number for random numb. :: iseed            :: 513
-------------------- Wavemaker definition ---------------------
Nonlinear order of wavemaker :: i_wmk            :: 2
Type (1: piston, 2: hinged)  :: igeom            :: 2
Rotation axis distance       :: d_hinge          :: 2.147d0
Time ramp                    :: iramp            :: 1
Time ramp duration (s)       :: Tramp            :: 3.0d0
----------------------- Numerical beach -----------------------
Absorption numerical beach   :: iabsnb           :: 1
Beginning front num. beach   :: xabsf            :: 0.8d0
Absorption strength front    :: coeffabsf        :: 1.d0
------------- Elevation/Velocity-Pressure probes --------------
Use of probes                :: iprobes          :: 1
Filename of probe positions  :: pro_file         :: prob.inp
---------------------- Time-integration -----------------------
Duration of the simulation   :: T_stop           :: 10.0d0
Time tolerance: RK 4(5)      :: toler            :: 1.e-4
Output frequency             :: f_out            :: 10.d0
--------------------------- Output ----------------------------
Output: 1-dim. ; 0-nondim.   :: idim             :: 1
free surface plot            :: i3d              :: 1
modes plot                   :: imodes           :: 0
wavemaker motion plot        :: iwmk             :: 1
Swense output 1='yes',0='no' :: i_sw             :: 1

and the beginning of the common_vars file:
! Number of modes
INTEGER, PARAMETER :: n1 = 30
INTEGER, PARAMETER :: n2 = 30
INTEGER, PARAMETER :: n3 = 32
! HOS nonlinearity order
INTEGER, PARAMETER :: mHOS = 3
! Dealiasing parameters
INTEGER, PARAMETER :: p1 = mHOS
INTEGER, PARAMETER :: p2 = mHOS

I try to change the value of n1,n2 and n3 but I still have the same kind of outputs... Do you have an idea to help me solve this problem?
And thank you very much for your work and for sharing it!

Many thanks,

Max.

**Comment by gducrozet** [comment]
Dear Max,

Just to clarify your problem : 
	- this is the file modes_HOS_SWENSE.dat which is empty? 
	- Do you have the same problem if you change the test-case (i.e. icase parameter in input file)?

Guillaume.
--
Guillaume Ducrozet
LHEEA Lab, Ocean and Wave Energy research group
Ecole Centrale de Nantes, Nantes, France
Tel : +33 240 371 645, Fax : +33 240 372 523

**Comment by Emix63** [comment]
Dear Guillaume,

-The modes_HOS_SWENSE.dat is actually not entirely empty but it is in this file that some characters are not recognized as numbers. I attach a screenshot of the modes_HOS_SWENSE.dat open in emacs
![screenshot_modes_hos_swense](https://cloud.githubusercontent.com/assets/10650018/8451771/038f6cfa-1fe6-11e5-9edc-6c05a10bfc0b.JPG)
- I have this problem when I tried either icase=31, 4, or 2. I didn't have any problem in 2D with the Irreg_2D benchmark case, but for example when I tried to have the swense output with the benchmark Irreg_3D, I have this problem.

Many thanks,

Max

**Comment by gducrozet** [comment]
Dear Max,

I had a look this morning and you were right, there were a mistake in the writing of the file.
I just committed a HOTFIX for this problem: https://github.com/LHEEA/HOS-NWT/commit/f653a9be2acdbd45b25474b983545918a5397e41

Could you confirm that it solves your issue, so that I close it here?

Regards,

Guillaume.

**Comment by Emix63** [comment]
Dear Guillaume,

It's working perfectly now! I tried two cases without any problem!

Thank you very much!

Max
